deploy:
  provider: releases
  api_key: $apikey
  skip_cleanup: true
  file_glob: true
  file: "/home/travis/build/NeumimTo/NTCore/target/NTCore-*-shaded.jar"
  on:
    branch: master
language: java
jdk:
  - oraclejdk8
